[plugin]
repository = "https://github.com/Hiroa/LazyGatherer.git"
commit = "9b5fb9e1f07101e387b88cbb6e1dbdf3f190fb00"
owners = ["Hiroa"]
project_path = "LazyGatherer"
changelog = """
Version 1.1.1: 
 - Fix UI initializing twice causing error.
 - Bring back dropdown in configuration.
"""